Fix CI pipeline

diff --git a/.github/workflows/c-cpp.yml b/.github/workflows/c-cpp.yml
--- a/.github/workflows/c-cpp.yml
+++ b/.github/workflows/c-cpp.yml
@@ -1,4 +1,4 @@
-name: CrashGuard CI v2
+name: CrashGuard CI
 
 on:
   push:
@@ -8,16 +8,23 @@ on:
 
 jobs:
   build:
-
     runs-on: ubuntu-latest
 
     steps:
     - uses: actions/checkout@v4
-    - name: configure
-      run: ./configure
-    - name: make
-      run: make
-    - name: make check
-      run: make check
-    - name: make distcheck
-      run: make distcheck
+
+    - name: Install dependencies
+      run: sudo apt-get update && sudo apt-get install -y build-essential && sudo apt install libcapstone-dev
+
+    - name: Compile main.c
+      run: gcc -Werror main.c -o crashguard -lcapstone
+
+    - name: Verify Build Success
+      run: |
+        if [ -f ./crashguard ]; then
+          echo "Build success."
+        else
+          echo "Build failed."
+          exit 1
+        fi
+        
